#!/bin/sh
#
# NAME
#
#   djvu2pdf - convert DjVu files to PDF
#
# SYNOPSIS
#
#   djvu2pdf <file>...
#
# DEPENDENCIS
#
#   ddjvu(1)
#


if [ "$*" ]
then
    for file
    do
        ddjvu -format=pdf "$file" "${file%.*}.pdf"
    done
else
    echo >&2 "usage: ${0##*/}: <file>..."
    exit 1
fi
