#!/bin/sh
#
# NAME
#
#   dtrx - extract archives
#
# SYNOPSIS
#
#   dtrx <file>...
#
# DESCRIPTION
#
#   Extract archives of different formats.  Named after the similar,
#   more featureful, Python script called "Do The Right Extraction".
#
# DEPENDENCIES
#
#   GNU tar(1), bunzip2(1), gunzip(1), unzip(1), 7z(1), uncompress(1)
#
# SEE ALSO
#
#   dtrx (https://brettcsmith.org/2007/dtrx/)
#

[ "$*" ] || {
    echo >&2 "usage: ${0##*/} <file>..."
    exit 1
}

for arg
do
   if [ -f "$arg" ]
   then
       case "$arg" in
           *.tar.bz2)   tar xvjf "$arg"   ;;
           *.tar.gz)    tar xvzf "$arg"   ;;
           *.bz2)       bunzip2 "$arg"    ;;
           *.rar)       unrar x "$arg"    ;;
           *.gz)        gunzip "$arg"     ;;
           *.tar)       tar xvf "$arg"    ;;
           *.tbz2)      tar xvjf "$arg"   ;;
           *.tgz)       tar xvzf "$arg"   ;;
           *.zip)       unzip "$arg"      ;;
           *.Z)         uncompress "$arg" ;;
           *.7z)        7z x "$arg"       ;;
           *.exe)       cabextract "$arg" ;;
           *)  echo >&2 "${0##*/}: no rule to extract '$arg'" ;;
       esac
   else
       echo >&2 "${0##*/}: '$arg' is not a valid file!"
   fi
done

#
# Elementary Bash completion function for dtrx(1).
#
# _dtrx() {
#     COMPREPLY=( $(compgen -A file -X '!(*.tar.bz2|*.tar.gz|*.bz2|*.rar|*.gz|*.tar|*.tbz2|*.tgz|*.zip|*.Z|*.7z|*.exe)' -- "${COMP_WORDS[COMP_CWORD]}") )
# }
#
# complete -F _dtrx dtrx
#
