#!/bin/sh
#
# NAME
#
#   ff-install - install the latest Firefox on Debian
#
# SYNOPSIS
#
#   ff-install
#
# DESCRIPTION
#
#   The Firefox version shipped with Debian stable is almost always
#   hilariously outdated.  This script fetches the latest tarball
#   distributed by Mozilla and unpacks it in the right directories.
#
# DEPENDENCIES
#
#   curl(1) and mktemp(1)
#

# Always run as root.
[ $(id -u) -eq 0 ] || exec sudo -- "$0" "$@"

set -eu

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir" >/dev/null 2>&1' EXIT
trap 'exit 2' HUP INT QUIT TERM

cd "$tmpdir"

echo >&2 "${0##*/}: fetching tarball"
curl -q#L "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" -o firefox.tar.bz2
tar xjf firefox.tar.bz2

echo >&2 "${0##*/}: installing .desktop file"
cat >/usr/share/applications/firefox.desktop <<entry
[Desktop Entry]
Name=Firefox
Comment=Web Browser
GenericName=Web Browser
X-GNOME-FullName=Firefox Web Browser
Exec=firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox
Categories=Network;WebBrowser;
Actions=ProfileManager;new-window;new-private-window;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Firefox
StartupNotify=false
entry

echo >&2 "${0##*/}: installing icons"
for size in 16 32 48 64 128
do
    cp -f "firefox/browser/chrome/icons/default/default$size.png" \
          "/usr/share/icons/hicolor/${size}x${size}/apps/firefox.png"
done

[ -d /opt/firefox ] && rm -rf /opt/firefox
cp -r firefox /opt/
ln -fs /opt/firefox/firefox /usr/bin

echo >&2 "${0##*/}: install complete"
