#!/bin/sh
#
# NAME
#
#   git-vaccum - garbage collect a git repository
#
# SYNOPSIS
#
#   git-vacuum
#
# DEPENDENCIES
#
#   git(1)
#

set -eu

reposize() {
    du -s "$(git rev-parse --show-toplevel)" | cut -f 1
}

before=$(reposize)

git remote prune origin
git repack
git prune-packed
git reflog expire --expire=1.month.ago
git gc --aggressive

after=$(reposize)
printf >&2 "\nRepository size reduced by %s%%.\n" \
    $(echo "scale=2; ($before - $after)*100/$before" | bc)
