#!/usr/bin/env bash
#
# NAME
#
#   inkconv - convert between vector graphics formats using Inkscape
#
# SYNOPSIS
#
#   inkconv <input> <output>
#
# DEPENDENCIES
#
#   inkscape(1)
#

[[ $# -lt 2 ]] && {
    echo >&2 "usage: ${0##*/} <input> <output>"
    exit 1
}

args=( "--export-area-drawing" )

# Choose converter according to extension.
case "${2##*.}" in
    svg|png|ps|eps|emf|wmf|xaml)
        args+=( "--export-type=${2##*.}" ) ;;
    pdf)
        args+=( "--export-type=pdf" "--export-pdf-version=1.4" ) ;;
    *)
        echo >&2 "${0##*/}: unknown output extension '.${2##*.}'"
        exit 1 ;;
esac
args+=( "--export-filename=$2" "$1" )

if inkscape "${args[@]}" &>/dev/null
then
    echo >&2 "${1} -> ${2}"
else
    echo >&2 "inkscape failed with arguments ${args[@]}"
    exit 1
fi
