#!/bin/sh
#
# NAME
#
#   open - open files using xdg-open and background properly
#
# SYNOPSI
#
#   open <file>
#   open <URL>
#
# SEE ALSO
#
#   openvt(1), xdg-open(1)
#

[ "$*" ] || {
    echo >&2 "usage: ${0##*/} <file>..."
    exit 1
}

export XDG_CURRENT_DESKTOP="X-Generic"
nohup xdg-open "$1" </dev/null >/dev/null 2>&1 &
