#!/usr/bin/env bash
#
# NAME
#
#   pdf-meta-edit - edit metadata of PDF files
#
# SYNOPSIS
#
#   pdf-meta-edit <file>
#
# DESCRIPTION
#
#   pdf-meta-edit is a wrapper script around PDFtk that will let you edit the
#   metadata (e.g., "subject", "title", etc.) of PDF files using $EDITOR.
#
# DEPENDENCIES
#
#   pdftk(1) and mktemp(1)
#

set -eu
set -o pipefail

[[ "$*" ]] || {
    echo >&2 "usage: ${0##*/} <file>"
    exit 1
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir" &>/dev/null' EXIT
trap 'exit 2' HUP INT QUIT TERM

meta="${tmpdir}/meta.txt"
pdftk "$1" dump_data_utf8 | grep '^Info' | sed '/^InfoBegin/! { s/^/  /; }' >"$meta"

# Generate these default keys if they're not available.
for key in "Author" "Subject" "Title" "Keywords"
do
    grep -q "InfoKey: ${key}" "$meta" || {
        echo "InfoBegin"
        echo "  InfoKey: ${key}"
        echo "  InfoValue:"
    } >>"$meta"
done

pdf="${tmpdir}/updated.pdf"
"${EDITOR:-vi}" "$meta"

pdftk "$1" update_info_utf8 <(sed 's/^  Info/Info/' "$meta") output "$pdf"
mv -f "$pdf" "$1"
