#!/bin/bash
#
# NAME
#
#   pdf-sed - edit PDFs using sed
#
# SYNOPSIS
#    
#   pdf-sed <sedexpr> <input> <output>
#
# DESCRIPTION
#
#   pdf-sed is a simple wrapper script around sed and PDFtk using which
#   you can edit PDFs.  It is useful for removing (text-only) watermarks
#   from PDFs downloaded from certain journals.
#
# DEPENDENCIES
#   
#   pdftk(1), sed(1)
#

set -e

[ $# -lt 3 ] && {
    echo >&2 "usage: ${0##*/} <sedexpr> <input> <output>"
    exit 1
}

# First, test the sed expression.
sed -e "$1" /dev/null

# Check if input file exists.
[ "${2##*.}" = "pdf" ] && [ -f "$2" ] || {
    echo >&2 "${0##*/}: input file '$2' does not exist or is an invalid file"
    exit 1
}

pdftk "$2" output - uncompress | sed -e "$1" | pdftk - output "$3" compress
