#!/bin/sh
#
# NAME
#
#   pdf2jpg - convert PDF files to JPEG
#
# SYNOPSIS
#
#   pdf2jpg [-d <dpi>] [-q <quality>] <file.pdf>
#
# OPTIONS
#
#   -d  <dpi>       set the DPI (default: 200)
#   -q  <quality>   set the compression (default: 90)
#
# DEPENDENCIS
#
#   magick(1)
#


dpi=200
quality=90
while getopts ":d:q:" opt
do
    case "$opt" in
        :)  echo >&2 "${0##*/}: $OPTARG requires an argument"
            exit 1 ;;
        \?) echo >&2 "${0##*/}: $OPTARG is not a valid option"
            exit 1 ;;
        d)  dpi="$OPTARG" ;;
        q)  quality="$OPTARG" ;;
    esac
done
shift $(( OPTIND - 1 ))

[ -f "$1" ] || {
    echo >&2 "usage: ${0##*/} [-d <dpi>] [-q <quality>] <file.pdf>"
    exit 1
}

exec magick -density "$dpi"     \
            -antialias "$1"     \
            -background white   \
            -alpha remove       \
            -alpha off          \
            -quality "$quality" \
            "${1%.*}"-%03d.jpg
