#!/usr/bin/env bash
#
# NAME
#
#   rainymood - play rain sounds from rainymood.com
#
# SYNOPSIS
#   
#   rainymood [<mood>]
#
# DESCRIPTION
#   
#   rainymood is a script that will play rain sounds from rainymood.com.
#   By default a random track (i.e., mood) will be selected.
# 
# DEPENDENCIES
#   
#   curl(1), mplayer(1)
#

[[ "$*" ]] || {
    set -- $(( 1 + RANDOM % 8 ))
}

mkdir -p "$HOME/.cache"
cache="$HOME/.cache/rainymood/$1.m4a"

[[ -f "$cache" ]] || {
    echo >&2 "${0##*/}: caching mood #$1"
    curl -q#kL -o "$cache" "https://www.rainymood.com/audio1110/${1}.m4a"
}

echo >&2 "${0##*/}: playing mood #$1"
exec mplayer -loop 0 -volume 100 -really-quiet "$cache" &>/dev/null
