#!/bin/sh
#
# NAME
#
#   spectrogram - make audio file spectrograms using FFmpeg and SoX
#
# SYNOPSIS
#
#   spectrogram <file> [<args>...]
#
# DESCRIPTION
#
#   spectrogram is a simple script to create a spectrogram of an audio
#   file using SoX. This can be useful to determine if the file has the
#   right bitrate as advertised.   If SoX fails to create the
#   spectrogram in the first attempt, the audio file is converted to
#   a PCM WAV file using FFmpeg.
#
# OPTIONS
#
#   All options accepted by SoX's spectrogram effect can be passed to
#   this script.  The first argument must however be the name of the
#   audio file.
#
# DEPENDENCIES
#
#   ffmpeg(1) and sox(1)
#

set -eu

[ "$*" ] || {
    echo >&2 "usage: ${0##*/} <file>... [<args>...]"
    sox >&2 --help-effect spectrogram
    exit 1
}

file="$1"; shift
set -- -y 513 -X 15 -l -o "$file.png" "$@"

if sox --info "$file" 2>&1 | grep -q "FAIL format"
then
    echo >&2 "${0##*/}: format error on '$file'; using ffmpeg"
    ffmpeg -y -i "$file" -f wav - | sox -t wav - -n spectrogram "$@" ||
        echo >&2 "${0##*/}: ffmpeg+sox failed on '$file'"
else
    sox "$file" -n spectrogram "$@"
fi
