#!/bin/sh
#
# NAME
#
#   srtextract - extract SubRip subtitles from video files
#
# SYNOPSIS
#
#   srtextract <file>...
#
# DESCRIPTION
#
#   srtextract is a script to extract SubRiP (.srt) files from videos
#   using ffmpeg(1).  If there are multiple subtitles, only the first
#   one is extracted.
#
# DEPENDENCIES
#
#   ffmpeg(1) and ffprobe(1)
#

[ "$*" ] || {
    echo >&2 "usage: ${0##*/} <file>..."
    exit 1
}

ffmpeg_srt_extract() {
    [ -n "$3" ] && out="${1%.*}_${3}.srt" || out="${1%.*}.srt"
    ffmpeg -loglevel -8 -i "$1" -map "$2" "$out" &&
        echo >&2 "${0##*/}: subtitle written to $out"
}

for f in "$@"
do
    ffmpeg_srt_extract "$f" $(
        ffprobe -i "$f" 2>&1 \
            | grep "subrip"  \
            | sed 's/^[ \t]*Stream #\([0-9]\{1,\}:[0-9]\{1,\}\)(\([^)]*\)).*/\1\t\2/p'
    )
done
