#!/bin/sh
#
# NAME
#
#   tarmk - extract tarballs and run make
#
# SYNOPSIS
#
#   tarmk [-m] <file> [<arg>...]
#
# OPTIONS
#
#   -m, --makefile-only     extract only the makefile
#
# DESCRIPTION
#
#   tarmk is a simple script to extract tarballs containing a makefile
#   into a temporary directory and run make with optional arguments.
#   This way, tarmk functions as a rudimentary package installer, e.g.,
#   to install sic (a simple IRC client), one could do
#
#   $ wget https://dl.suckless.org/tools/sic-1.2.tar.gz
#   $ tarmk sic-1.2.tar.gz install
#
# DEPENDENCIES
#
#   mktemp(1), tar(1)
#

set -e

exdir=$(mktemp -d)
trap 'cd / && rm -rf "$exdir" >/dev/null 2>&1' EXIT
trap 'exit 2' HUP INT QUIT TERM

case "$1" in
    -m|--makefile-only)
        shift; path="$(tar -tf "$1" | grep -i makefile | head -n 1)"
        tar -C "$exdir" -xvzf "$1" "$path" ;;
    -*|"")
        echo >&2 "usage: ${0##*/} <file> [<arg>...]"
        exit 1 ;;
    *)
        tar -C "$exdir" -xvzf "$1" ;;
esac

makefile=$(find "$exdir" -type f -iname 'makefile' -print -quit)
shift; cd "${makefile%/*}" && make "$@"
