#!/bin/sh
#
# NAME
#
#   texstrip - remove comments from a TeX file.
#
# SYNOPSIS
#
#   texstrip [<args>] [<file>]
#
# DESCRIPTION
#
#   texstrip strips all comments from a TeX file.  All arguments that
#   can be passed to sed(1) can be passed to texstrip.
#

sed -e '
    # What are the chances that your .tex file contains the word
    # __TEXSTRIP_PERCENT?
    s/%[ \t]*$/__TEXSTRIP_PERCENT_EOL/
    s/\\%/__TEXSTRIP_PERCENT/g
    /^[ \t]*%/d
    s/%.*//
    s/[ \t]\\{1,\}$//
    s/__TEXSTRIP_PERCENT_EOL/%/
    s/__TEXSTRIP_PERCENT/\\%/g
' "$@" | tr -s '\n'
