#!/bin/sh
#
# NAME
#
#   upload - upload files to a server using SSH
#
# SYNOPSIS
#
#   upload [-z] [-s <name>] <file>
#
# DESCRIPTION
#
#   upload is a shell script to upload files to an SSH server and print
#   out an HTTP-accessible URL.  To use upload, set the UPLOAD_SRC_HEAD
#   and UPLOAD_SRC_HTTP environment variables, e.g.,
#
#       UPLOAD_SRC_HEAD="user@example.com:public"
#       UPLOAD_SRC_HTTP="https://example.com/user/public"
#
# OPTIONS
#
#     -s <name>   upload file to server with the given name
#     -z          make a Zip archive before uploading
#
# DEPENDENCIES
#
#   scp(1) and zip(1)
#

[ "$UPLOAD_SRC_HEAD" ] && [ "$UPLOAD_SRC_HTTP" ] || {
    echo >&2 "${0##*/}: \$UPLOAD_SRC_HEAD and/or \$UPLOAD_SRC_HTTP not set; exiting."
    exit 1
}

usezip= base=
while getopts ":zs:" var
do
    case "$var" in
        z)  usezip="yes" ;;
        s)  base="$OPTARG" ;;
        :)  echo >&2 "${0##*/}: -$OPTARG requires an argument"
            exit 1 ;;
        \?) echo >&2 "${0##*/}: -$OPTARG is not a valid option"
            exit 1 ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$1" ] && [ -e "$1" ] || {
    echo >&2 "${0##*/}: file or directory required"
    echo >&2 "${0##*/} [-z] [-s <name>] <file>"
    exit 1
}

[ "$base" ] || base=$(basename "$1")

: ${TMPDIR:=/tmp}
[ "$usezip" = "yes" ] && {
    if zip -r "$TMPDIR/$base.zip" "$1" >&2
    then
        base="$base.zip"
        set -- "$TMPDIR/$base"
        trap 'rm -rf "$1" >/dev/null 2>&1' EXIT
        trap 'exit 2' HUP INT QUIT TERM
    else
        echo >&2 "${0##*/}: zip failed on '$1'"
        exit 1
    fi
}

if scp -BCpr "$1" "$UPLOAD_SRC_HEAD/$base" >&2
then
    echo "$UPLOAD_SRC_HTTP/$base"
else
    echo >&2 "${0##*/}: upload failed!"
    exit 1
fi
