#!/bin/sh
#
# NAME
#
#   x230t-rotate - rotate ThinkPad X230t's display
#
# SYNOPSIS
#
#   x230t-rotate [<rotation>]
#
# DESCRIPTION
#
#   This is a display rotation script to be used with a ThinkPad X230t
#   tablet.  With trivial modifications one can also use it with other
#   tablets.  The supplied rotation can be the usual ones defined by
#   xrandr, i.e., "normal", "inverted", "left", and "right".
#   Additionally, we define the following two rotations:
#
#       flip        switch between normal and inverted, or left and right
#       sideways    switch between normal and left, or inverted and right
#
#   Since switching between rotations requires knowledge of current
#   rotation, the current state is always written to ~/.x230t-rotation
#   at the end of execution.  The rotation matrices were adapted from
#
#       https://gist.github.com/mildmojo/48e9025070a2ba40795c
#
# DEPENDENCIES
#
#   xrandr(1) and xinput(1)
#

# Check the output of xrandr(1) and xinput(1) and change accordingly.
# We could parse the outputs, but that'd create an unnecessary overhead.
screen="LVDS1"
stylus="Wacom ISDv4 E6 Pen g"
finger="Wacom ISDv4 E6 Finger touch"

matrix="Coordinate Transformation Matrix"
state="$HOME/.x230t-rotation"

[ -f "$state" ] && current=$(cat "$state") || set -- "normal"

case "$1" in
    n*) set -- "normal"   ;;
    i*) set -- "inverted" ;;
    l*) set -- "left"     ;;
    r*) set -- "right"    ;;
    f*) case "$current" in
            n*) set -- "inverted" ;;
            i*) set -- "normal"   ;;
            l*) set -- "right"    ;;
            r*) set -- "left"     ;;
        esac
        ;;
    s*) case "$current" in
            n*) set -- "left"     ;;
            i*) set -- "right"    ;;
            l*) set -- "normal"   ;;
            r*) set -- "inverted" ;;
        esac
        ;;
    *)  set -- "normal" ;;
esac

xrandr --output "$screen" --rotate "$1"

case "$1" in
    normal)
        xinput set-prop "$stylus" "$matrix" 1 0 0 0 1 0 0 0 1
        xinput set-prop "$finger" "$matrix" 1 0 0 0 1 0 0 0 1
        ;;
    inverted)
        xinput set-prop "$stylus" "$matrix" -1 0 1 0 -1 1 0 0 1
        xinput set-prop "$finger" "$matrix" -1 0 1 0 -1 1 0 0 1
        ;;
    left)
        xinput set-prop "$stylus" "$matrix" -1 1 1 0 0 0 0 1
        xinput set-prop "$finger" "$matrix" -1 1 1 0 0 0 0 1
        ;;

    right)
        xinput set-prop "$stylus" "$matrix" 0 1 0 -1 0 1 0 0 1
        xinput set-prop "$finger" "$matrix" 0 1 0 -1 0 1 0 0 1
        ;;
esac

# Write current rotation to state file.
echo "$1" >"$state"
